[FE] SnackBar 컴포넌트 구현
Joribok/Joribok pull request #10
Opened 2022-12-16 15:17 UTC by liswktjs

###  개발한 기능 목록 
- 스낵바 구현 
- 스낵바에 애니메이션 추가 

### 구현된 UI 

https://user-images.githubusercontent.com/60773373/208127595-76b85eda-8c6e-4dba-b315-61ffcf35fe52.mov

### 공유사항 

- _document 
Next의 경우 이전 저희가 리액트에서 진행했던 public 하위에 있는 index.html에서 진행 했던 작업들을 _document.tsx라는 파일에서 진행해야 합니다. 그래서 Portal을 만들기 위해서 _document의 하위에 id가 snack-bar인 것을 삽입하였습니다 
참고자료 : https://nextjs.org/docs/advanced-features/custom-document
- next에서 portal 만들기 
기존에 리액트에서 진행하던 방식대로 document.querySelector를 통해 element를 찾고자 하게 되면 Next는 `document is not defined`라는 에러를 뿜게 됩니다. 이는 Next가 ssr이라는 것에 기인한 문제라고 합니다. 초기 SSR을 만들 때에 Next에게는 자바스크립트가 실행되기 전입니다 이후 CSR과정을 거칠때 Next에서 window 하위의 항목들을 접근이 가능해집니다. 그래서 추가적인 작업들이 필요합니다
참고자료: https://www.univdev.page/posts/nextjs-portal/ 
- className으로 애니메이션하기 
이 부분에 대해서는 고민을 많이하였는데요. 어차피 keyframe으로 css생성해서 애니메이션을 적용해야한다면 className을 통해서 자연스럽게 부드럽게 보여지는 애니메이션이 좋을 것 같다는 생각에 className으로 애니메이션 생성 도전해보았습니다 후후

close #2

2022-12-17 02:43 UTC, LAH1203 requested changes
샐리 수고하셨습니다! next는 포탈을 하려면 복잡하게 해야하는군요.. 🥲

이것저것 테스트해보면서 좀 이상한 부분이 있었는데, 일단은 그냥 일반 div나 button에 onClick을 달아도 먹지가 않더라고요? 이 부분도 같이 확인해주시면 좋을 것 같아요.

2022-12-17 02:43 UTC, LAH1203 commented on frontend/src/components/SnackBar/animation.module.css
> +  transition: visibility 200ms ease-in-out, opacity 200ms ease-in-out, transform 200ms ease-in-out;
`all`로 해도 동작은 같을 것 같은데 이렇게 다 세분화해서 적용시켜준 이유가 있나요?

2022-12-17 02:43 UTC, LAH1203 commented on frontend/src/components/SnackBar/index.stories.tsx
> +    }, 1000);
이렇게만 하면 저는 전에 스낵바가 빠르게 나오는 경우에 이전의 타임아웃 때문에 씹히는 경우도 종종 있었는데, useEffect 단에서 clearTimeout 해주는 부분을 추가하는 건 어떻게 생각하시나용?

2022-12-17 02:43 UTC, LAH1203 commented on frontend/src/hooks/useSnackBar.tsx
> +    }, 1000);
여기도 이전 코멘트와 같은 맥락입니당!

2022-12-17 02:43 UTC, LAH1203 commented on frontend/src/components/SnackBar/index.tsx
> +import styles from './animation.module.css';
샐리꺼 받아와서 코드 보고 있는데, css 파일을 vscode가 모듈로 인식을 못하네요! 설정을 추가해야 할 것 같아요.

2022-12-17 02:43 UTC, LAH1203 commented on frontend/src/components/SnackBar/index.tsx
> +  const [snackBarClassName, setSnackBarClassName] = useState('');
snackBarState에 따라 바뀌니 className 할당하는 부분에 삼항연산자 문 자체가 있어도 될 것 같은데 이렇게 따로 상태로 관리하신 이유가 있을까요?

2022-12-17 02:43 UTC, LAH1203 commented on frontend/src/components/SnackBar/index.stories.tsx
> +  }, []);
여기 디펜던시 부분에 `React Hook useEffect has a missing dependency`가 뜨네요..! 디펜던시에 setter를 추가하든 아니면 경고를 하지 않도록 설정이나 주석을 추가해야 할 것 같아유

2022-12-17 03:16 UTC, liswktjs commented on frontend/src/components/SnackBar/animation.module.css
> +  transition: visibility 200ms ease-in-out, opacity 200ms ease-in-out, transform 200ms ease-in-out;
엇 all로 하면 다 적용이 되나요? 그 점은 몰랐군요 다시 수정해서 반영해보겠습니다

2022-12-17 05:08 UTC, usageness requested changes
고생 많았습니다 샐리!
공유해주신 내용도 잘 읽었어요~
몇 가지 코멘트만 확인해주세요 ㅎㅎ

2022-12-17 05:08 UTC, usageness commented on frontend/src/components/SnackBar/animation.module.css
> +  visibility: hidden;
display 속성과 visiblility 속성을 동시에 주신 이유가 있나요?

2022-12-17 05:08 UTC, usageness commented on frontend/src/util/CreatePortal.tsx
> +  const portalRef = useRef<Element | null>(null);
useRef의 타입으로 Element와 null을 함께 받아주신 이유가 있을까요?

2022-12-17 05:43 UTC, liswktjs commented on frontend/src/components/SnackBar/index.stories.tsx
> +    }, 1000);
추가하도록 하겠습니다!

2022-12-17 05:43 UTC, liswktjs commented on frontend/src/components/SnackBar/index.tsx
> +import styles from './animation.module.css';
흠.... 설정의 세계 험난하군요 한 번 설정 건드려보겠습니다

2022-12-17 05:44 UTC, liswktjs commented on frontend/src/components/SnackBar/index.tsx
> +  const [snackBarClassName, setSnackBarClassName] = useState('');
정확하게 실험한건 아니지만, className에 삼항연산자로 했을 때 작동을 하지 않더라고요 그래서 일단은 상태값으로 className을 지정해주었습니다

2022-12-17 05:46 UTC, liswktjs commented on frontend/src/components/SnackBar/animation.module.css
> +  visibility: hidden;
혹시나 보여질 미연의 상황을 방지하기 위해서 둘다 적용해주게 되었습니다 
정확히는 , display의 경우 요소가 존재하지 않는 것처럼 보여주는 것인데 어느 인강에서 가끔씩 해당 display가 먹히지 않는 경우가 있다고 들어서 visibility hidden을 해당 케이스에 대비해서 주었습니다

2022-12-17 05:47 UTC, liswktjs commented on frontend/src/util/CreatePortal.tsx
> +  const portalRef = useRef<Element | null>(null);
최초의 값은 null(document를 못찾는 상태)여서 null로 넣어주었습니다 해당 구문을 넣어주지 않으면 타입에러가 났던 기억이... 정확히 확인해보겠습니다

2022-12-17 07:29 UTC, liswktjs commented on frontend/src/components/SnackBar/index.tsx
> +import styles from './animation.module.css';
https://nextjs.org/docs/basic-features/built-in-css-support 해당 부분에서 next에서는 css module을 기본으로 제공하고 있다고 합니다 아무래도 ts잘못인것 같네요 관련 설정을 더 찾아보겠습니다

2022-12-17 07:39 UTC, liswktjs commented on frontend/src/components/SnackBar/index.tsx
> +  const [snackBarClassName, setSnackBarClassName] = useState('');
지금 다시 실험해보니, 해당 방식으로 동작시켜야 애니메이션이 적용되네요😅 상태값으로 관리할 때에는 리렌더링이 되는데 className으로 들어가서 관리하면 감지를 못하는걸까요?

2022-12-17 07:40 UTC, liswktjs commented on frontend/src/components/SnackBar/index.stories.tsx
> +  }, []);
스토리북에 set함수를 넣어주었습니다!

2022-12-17 07:40 UTC, liswktjs commented on frontend/src/util/CreatePortal.tsx
> +  const portalRef = useRef<Element | null>(null);
다시 한번 확인해보니 최초의 값이 Null일 수있어서 Null을 넣어야 타입에러가 발생하지 않네요!

2022-12-17 07:43 UTC, liswktjs commented
실제화면에서 snackbar을 동작시키도록 코드를 수정했더니, 스토리북에서는 애니메이션이 안 보이게 되었습니다 ㅠ 
실제화면에서는 애니메이션이 정상적으로 작동합니다!

2022-12-17 08:07 UTC, usageness commented on frontend/src/components/SnackBar/animation.module.css
> +  visibility: hidden;
오... 처음 들어보는데 혹시 관련 자료가 있다면 저도 알려주세요~~

2022-12-17 08:25 UTC, usageness commented on frontend/src/util/CreatePortal.tsx
> +  const portalRef = useRef<Element | null>(null);
Ref의 current를 직접 접근하게 되어서 발생하는 타입 에러인 것 같아요.
이렇게 useRef를 사용하지 않으면 코드를 줄일 수 있지 않을까요?

```suggestion
  const CreatePortal = ({ modalId, children }: PropsWithChildren<CreatePortalProps>) => {
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  const target = document.querySelector<HTMLElement>(`#${modalId}`);
  return mounted && target ? ReactDOM.createPortal(children, target) : <></>;
};
```

2022-12-18 07:40 UTC, LAH1203 commented on frontend/src/components/SnackBar/index.tsx
> +  const [snackBarClassName, setSnackBarClassName] = useState('');
흐음.. 그건 정말 왜 그런걸까요..? 여태까지 삼항으로 바로 넣는 방법으로 리액트에선 사용해왔는데, next는 다른가?! 좀 더 알아봐야겠네용 😵‍💫

2022-12-18 07:41 UTC, LAH1203 approved these changes
수정사항 확인했습니다~ 수고하셨습니다!

2022-12-21 09:29 UTC, liswktjs commented on frontend/src/util/CreatePortal.tsx
> +  const portalRef = useRef<Element | null>(null);
반영해서 수정했습니다!

2022-12-21 12:20 UTC, usageness approved these changes
변경사항 확인했습니다!

2022-12-21 12:25 UTC, merged