[FE] Input 컴포넌트 구현
Joribok/Joribok pull request #11
Opened 2022-12-16 16:58 UTC by usageness

###  개발한 기능 목록 
- Input 컴포넌트 구현

### 구현된 UI 

![image](https://user-images.githubusercontent.com/28296575/208149532-bbbb6308-845a-4c2a-b7b8-76f2af5f0364.png)

### 공유사항 

- 기본 컴포넌트를 만들때 원래 태그가 가지고 있는 값들을 모두 지원해주기 위해 `rest parameter`를 사용하였습니다. 필요하다면 이런식으로 처리해주는게 좋을 것 같네요.
- figma 시안에 따라 인풋에 들어가는 색상이 고정되어 있어서 색상은 따로 변경시켜주지 않도록 했습니다.

close #4

2022-12-17 02:58 UTC, LAH1203 requested changes
세지 수고하셨습니다! 간단하게 코멘트 남겼습니다 :) 확인 부탁드려요~

2022-12-17 02:58 UTC, LAH1203 commented on frontend/src/components/Input/index.styles.tsx
> +    border-style: solid;
요건 이렇게 나눠주신 이유가 있나요?

2022-12-17 02:58 UTC, LAH1203 commented on frontend/src/components/Input/index.tsx
> +  }
early return을 사용하면 좀 더 보기 편하고 중복을 줄일 수 있지 않을까요?.?

```suggestion
  if (hasUnderline) {
    return <S.UnderlineInput type={type} isValid={isValid} {...inputAttribute} />;
  }
  
  return <S.Input type={type} isValid={isValid} {...inputAttribute} />;
```

2022-12-17 05:09 UTC, usageness commented on frontend/src/components/Input/index.tsx
> +  }
나중에 인풋이 추가될때를 대비해서 switch 문으로 작성해줬는데,
굳이 지금 고려할 필요는 없겠네요 :) 수정하겠습니다!

2022-12-17 05:55 UTC, liswktjs requested changes
몇가지 코멘트 남겼습니다! 확인부탁드려요~

2022-12-17 05:55 UTC, liswktjs commented on frontend/src/components/Input/index.styles.tsx
> +    background: ${isValid ? theme.colors.WHITE_100 : theme.colors.RED_200};
RED_100으로 하는건 어떨까요? 너무 빨간것 같기도하고.... 한 번 고려해주세요!

2022-12-17 05:55 UTC, liswktjs commented on frontend/src/components/Input/index.styles.tsx
> +  border-radius: 4px;
rem으로 통일 가시죠

2022-12-17 05:55 UTC, liswktjs commented on frontend/src/components/Input/index.styles.tsx
> +    border-bottom: 1px solid ${theme.colors.BLACK_500};
rem으로 px 통일하는거 어떨까요?

2022-12-17 05:55 UTC, liswktjs commented on frontend/src/components/Input/index.tsx
> +  React.DetailedHTMLProps<React.InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>) => {
width, height와 같은 값들을 모두 prop으로 넘겨서 설정하게 되는걸까요?

2022-12-17 05:55 UTC, liswktjs commented on frontend/src/components/Input/index.tsx
> +  React.DetailedHTMLProps<React.InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>) => {
저희가 input 사용되는 곳, 로그인 회원가입에서 input크기가 설정되어 있어서 해당 경우에 대한 스타일을 따로 객체로 선언해두고 똑같이 width와 height값을 넣어줘도 좋을 것 같아요

2022-12-17 08:33 UTC, usageness commented on frontend/src/components/Input/index.styles.tsx
> +    border-style: solid;
border 단축 속성으로 표시하면 width도 기재해줘야 될 것 같아서 나눠주었는데,
생략할 수 있는 값이었네요! border로 합쳐볼게요~

2022-12-17 08:34 UTC, usageness commented on frontend/src/components/Input/index.styles.tsx
> +    background: ${isValid ? theme.colors.WHITE_100 : theme.colors.RED_200};
RED_100도 괜찮네요! 이걸로 적용할게요. 
![image](https://user-images.githubusercontent.com/28296575/208233427-85500e97-0e14-4cf3-b41a-86faec03db77.png)

2022-12-17 08:38 UTC, usageness commented on frontend/src/components/Input/index.styles.tsx
> +  border-radius: 4px;
root의 font-size가 가변이라서 rem으로 두면 창 크기 따라 디자인이 변해요.
이건 px로 고정시키는게 좋을 것 같아요.

2022-12-17 08:38 UTC, usageness commented on frontend/src/components/Input/index.styles.tsx
> +    border-bottom: 1px solid ${theme.colors.BLACK_500};
위의 코멘트와 동일합니다~

2022-12-17 08:42 UTC, usageness commented on frontend/src/components/Input/index.tsx
> +  React.DetailedHTMLProps<React.InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>) => {
음... 이건 기본적으로 사용되는 컴포넌트를 만든거라 여기서 width, height를 설정해 줄 필요가 있을까요?
사용되는 곳에 따라서 다르게 적용되어야 할 것 같아요.
혹시 나중에 중복이 발생하게되면 추출해주는 식으로 가면 어떨까요?

2022-12-17 11:33 UTC, usageness commented
수정 사항들 적용해봤습니다~~ 확인 부탁드릴게요 😊

2022-12-18 07:42 UTC, LAH1203 approved these changes
수정사항 확인했습니다~ 수고하셨습니다!

2022-12-19 14:49 UTC, liswktjs approved these changes

2022-12-19 15:03 UTC, merged