[FE] 헤더 구현
Joribok/Joribok pull request #12
Opened 2022-12-19 06:14 UTC by LAH1203

## 개발한 기능 목록

- 헤더 컴포넌트 구현
- 슬라이더 구현

<img src="https://user-images.githubusercontent.com/57928612/208359733-9175b62f-e5aa-42e7-8968-709f9cd3f8a1.png" width="425px" />
<img src="https://user-images.githubusercontent.com/57928612/208359608-86d220cb-d026-441b-a4c0-4eaf7f33144a.png" width="425px" />

close #7

2022-12-21 10:37 UTC, liswktjs requested changes
안녕하세요 하리! pr리뷰가 늦어져서 죄송합니다 🥲
하리 Header 애니메이션하고 Slider 애니메이션 이쁘네요 스르륵 느낌 좋아요 

코멘트 남긴 것들은 네이밍과 상수관련입니다!

2022-12-21 10:37 UTC, liswktjs commented on frontend/src/components/Header/Slider/Login/index.tsx
> +            d="M16.5938 24.2568C16.5938 24.9903 16.8851 25.6938 17.4038 26.2124C17.9224 26.7311 18.6259 27.0225 19.3594 27.0225C20.0929 27.0225 20.7963 26.7311 21.315 26.2124C21.8336 25.6938 22.125 2
오우....! 상수로 빼서 관리하는건 어떨까요? 하하

2022-12-21 10:37 UTC, liswktjs commented on frontend/src/components/Header/Slider/NotLogin/index.tsx
> +const NotLogin = () => {
LogOut 네이밍은 어떤가요? 사실 그게 그거긴 하지만 🤔

2022-12-21 10:37 UTC, liswktjs commented on frontend/src/components/Header/Slider/NotLogin/index.tsx
> +            d="M16.5938 24.2568C16.5938 24.9903 16.8851 25.6938 17.4038 26.2124C17.9224 26.7311 18.6259 27.0225 19.3594 27.0225C20.0929 27.0225 20.7963 26.7311 21.315 26.2124C21.8336 25.6938 22.125 2
얘도 위와 동일합니다!

2022-12-21 10:37 UTC, liswktjs commented on frontend/src/components/Header/Slider/index.styles.tsx
> +  aspect-ratio: 1 / 1;
오 해당 속성은 처음 보네요 svg 비율을 맞출려고 사용한 것일까요?

2022-12-21 10:37 UTC, liswktjs commented on frontend/src/store/index.ts
> +const loginStateAtom = atom({
id와 nickname도 같이 관리한다면 Atom이름을 userStateAtom으로 하는건 어떨까요?

2022-12-21 10:37 UTC, liswktjs commented on frontend/src/components/Header/Slider/index.styles.tsx
> +  z-index: 999;
theme에 같이 관리하는게 어떨까요?

2022-12-21 10:37 UTC, liswktjs commented on frontend/src/components/Header/Slider/index.tsx
> +    <S.Dimmer onClick={close}>
close가 보편적인 단어라서 좀 더 자세히 함수명을 만드는게 어떨까요? closeSlider? 어떠신가요

2022-12-21 10:37 UTC, liswktjs commented on frontend/src/hooks/useClosingState.ts
> +const useClosingState = (animationTime: number, setOffFunc: () => void) => {
해당 state에서 close보다 더 자세한 이름으로 관리하면 좋을 것 같아요! 
closingState라는 이름만 보면 어떤 것과 관련된 close인지 한번에 감이 안잡힐 것 같습니다

2022-12-21 10:37 UTC, liswktjs commented on frontend/src/hooks/useHeader.ts
> +  }, 50);
👍👍 애니메이션까지 역시 하리

2022-12-21 10:37 UTC, liswktjs commented on frontend/src/hooks/useHeader.ts
> +  // eslint-disable-next-line react-hooks/exhaustive-deps
어떤 Lint에러가 났던 걸까요? 😆

2022-12-22 10:03 UTC, LAH1203 commented on frontend/src/components/Header/Slider/Login/index.tsx
> +            d="M16.5938 24.2568C16.5938 24.9903 16.8851 25.6938 17.4038 26.2124C17.9224 26.7311 18.6259 27.0225 19.3594 27.0225C20.0929 27.0225 20.7963 26.7311 21.315 26.2124C21.8336 25.6938 22.125 2
vscode 상에서는 한줄로 표시돼서 그렇게 길어보이지 않아 놔뒀는데 여긴 이렇게 보이는군요?! assets로 분리해보겠습니당

2022-12-22 10:03 UTC, LAH1203 commented on frontend/src/components/Header/Slider/NotLogin/index.tsx
> +const NotLogin = () => {
로그아웃은 관습 상 로그인 되어있는 상태를 해제한다라는 느낌이 있어서 로그인 되어있지 않다는 상태를 표현하기엔 조금 어색한 감이 있는 것 같아요..

2022-12-22 10:03 UTC, LAH1203 commented on frontend/src/components/Header/Slider/NotLogin/index.tsx
> +            d="M16.5938 24.2568C16.5938 24.9903 16.8851 25.6938 17.4038 26.2124C17.9224 26.7311 18.6259 27.0225 19.3594 27.0225C20.0929 27.0225 20.7963 26.7311 21.315 26.2124C21.8336 25.6938 22.125 2
분리했습니당

2022-12-22 10:03 UTC, LAH1203 commented on frontend/src/components/Header/Slider/index.styles.tsx
> +  aspect-ratio: 1 / 1;
닫기 버튼에서는 svg를 사용하지 않아서 svg 비율을 맞추기 위함은 아니었고요..! 닫기 버튼 자체의 비율을 1대1로 맞춰 정사각형으로 만들어주기 위함이었습니당
`aspect-ratio`는 무언가 요소의 width와 height의 비율을 조정할 때 주로 사용하는 css 속성입니닷 ! 제가 아주 애용하고 있습니당ㅎㅎ

2022-12-22 10:03 UTC, LAH1203 commented on frontend/src/store/index.ts
> +const loginStateAtom = atom({
좋습니다! 같이 수정할게유

2022-12-22 10:03 UTC, LAH1203 commented on frontend/src/components/Header/Slider/index.styles.tsx
> +  z-index: 999;
저는 z-index는 레이어마다 다르게 적용되니까 아직 전역으로 뺄 필요성은 크게 느끼지 못했는데, 혹시 샐리는 전역으로 빼서 관리하자고 생각하신 이유가 있나요?

2022-12-22 10:03 UTC, LAH1203 commented on frontend/src/components/Header/Slider/index.tsx
> +    <S.Dimmer onClick={close}>
넵 같이 수정하겠습니다

2022-12-22 10:03 UTC, LAH1203 commented on frontend/src/hooks/useClosingState.ts
> +const useClosingState = (animationTime: number, setOffFunc: () => void) => {
딱히 어떤 것과 관련되어 있는 close라기보다는 닫히는 상태 애니메이션을 제공하기 위해 `닫히는 중`이라는 상태를 제공하는 커스텀 훅입니다. 여러 곳에서 공용으로 사용할 수 있고, 닫히는 중이라는 상태를 제공하는 커스텀 훅이라는 의미에서 이런 이름을 사용하였습니다. 저는 이 이름이 지금까지 생각했던 것 중에서는 가장 적합하다고 생각했는데, 혹시 샐리는 생각나는 더 좋은 이름이 있으신가요?

2022-12-22 10:03 UTC, LAH1203 commented on frontend/src/hooks/useHeader.ts
> +  // eslint-disable-next-line react-hooks/exhaustive-deps
밑에서 사용하는 useMemo 훅으로 감싼 함수가 특정한 경우에만 실행되길 바라서 디펜던시에 원하는 값을 넣었더니 '필요한 값만 넣고 필요하지 않은 그 값은 빼!'라고 린트가 그러더라고요..? 그래서 주석을 달아주었습니다ㅎㅎ

2022-12-22 10:07 UTC, LAH1203 commented on frontend/src/hooks/useClosingState.ts
> +const useClosingState = (animationTime: number, setOffFunc: () => void) => {
(아닛 코멘트가 지워졌잖아..?! 기억을 더듬어... 다시 달아볼게요....)
이 커스텀 훅은 특정 컴포넌트와만 관련된 커스텀 훅이 아닌 여러 컴포넌트에서 다양하게 쓰일 수 있는, 닫히는 애니메이션 재생을 위해 `닫히는 중`이라는 상태를 제공하는 커스텀 훅입니다. 때문에 저는 닫히는 중이라는 상태를 제공하는 커스텀 훅이라는 이름에서 `useClosingState`라는 이름이 가장 적절하다고 생각해서 이렇게 만들었는데, 혹시 샐리는 생각나는 더 적절한 이름이 있으신가요?.?

2022-12-22 10:33 UTC, usageness approved these changes
고생하셨습니다 하리~~~ 이건 바로 approve 드려도 되겠네요!!

2022-12-22 10:33 UTC, usageness commented on frontend/src/components/Header/Slider/NotLogin/index.tsx
> +const NotLogin = () => {
그럼 LogOff 는 어떤가요? 😄😄

2022-12-22 10:33 UTC, usageness commented on frontend/src/components/Header/Slider/index.stories.tsx
> +      defaultViewport: 'iphone12',
👍

2022-12-22 10:33 UTC, usageness commented on frontend/src/components/Header/index.tsx
> +          <span />
혹시 요 `<span />` 의 용도가 무엇일까요?

2022-12-22 10:33 UTC, usageness commented on frontend/src/hooks/useClosingState.ts
> +const useClosingState = (animationTime: number, setOffFunc: () => void) => {
혹시 닫히는 중이라는 상태는 어디어디에 쓰일 수 있을까요?
당장 생각나는건 모달과 슬라이더 정도네요.

2022-12-22 10:33 UTC, usageness commented on frontend/src/components/Header/Slider/index.styles.tsx
> +    transform: translate3d(100%, 0, 0);
이제는 습관화 되어버린 3d...! 굿굿

2022-12-23 03:10 UTC, LAH1203 commented on frontend/src/components/Header/Slider/NotLogin/index.tsx
> +const NotLogin = () => {
오호 그거 괜찮네요 login이랑 비슷하게 logoff로 수정해볼게유

2022-12-23 03:10 UTC, LAH1203 commented on frontend/src/hooks/useClosingState.ts
> +const useClosingState = (animationTime: number, setOffFunc: () => void) => {
한다면 스낵바에도 적용할 수는 있을 것 같은데 샐리가 이미 스낵바를 만든 상태라 지금 적용은 힘들겠네용..ㅎㅎ

2022-12-23 03:10 UTC, LAH1203 commented on frontend/src/components/Header/index.tsx
> +          <span />
햄버거 버튼에 막대기 선입니당! svg 안쓰고 만들었어용 😆

2022-12-23 05:19 UTC, liswktjs commented on frontend/src/components/Header/Slider/index.styles.tsx
> +  z-index: 999;
slider는 모든 페이지에서 보여지는 것이라서 theme으로 선언해두고 나면,  나중에 페이지 마다 zIndex를 적용해야할 때에 일일이 어떤 zindex가 있었지 하고 찾아볼 필요가 없더라고요

2022-12-23 05:21 UTC, liswktjs commented on frontend/src/hooks/useClosingState.ts
> +const useClosingState = (animationTime: number, setOffFunc: () => void) => {
그러게요 snackBar말고 더 사용하는데가...... 어딨지 🤔 이점은 조금 고민이 되네요 하하

2022-12-23 05:23 UTC, liswktjs commented on frontend/src/components/Header/Slider/Login/index.tsx
> +            d="M16.5938 24.2568C16.5938 24.9903 16.8851 25.6938 17.4038 26.2124C17.9224 26.7311 18.6259 27.0225 19.3594 27.0225C20.0929 27.0225 20.7963 26.7311 21.315 26.2124C21.8336 25.6938 22.125 2
제가 알기론 Next가 정적 asset들은 public하위에 두면 따로 import할 필요없이 src={/icon}이런식으로 접근이 가능한걸로 압니다! 
https://nextjs.org/docs/basic-features/static-file-serving

2022-12-23 05:24 UTC, liswktjs requested changes
Next의 기능을 활용해보는 것도 좋을 것 같아요! 
SSR이다 보니 정적 asset들을 사용하기 편하도록 조정해두었더라고요

2022-12-23 05:24 UTC, liswktjs commented on frontend/src/components/Header/Slider/Login/index.tsx
> +import loginSVG from '@/assets/svg/user/login.svg';
https://nextjs.org/docs/basic-features/static-file-serving

해당 부분 참고해서 적용해도 좋을 것 같아요!

2022-12-23 11:39 UTC, LAH1203 commented on frontend/src/components/Header/Slider/Login/index.tsx
> +import loginSVG from '@/assets/svg/user/login.svg';
이렇게 하면 문제점이 next js 자체에서 public 경로로 지정한 Image는 무조건 width랑 height를 달지 않으면 에러가 나도록 만들어두었는데, 그 width랑 height가 숫자만 전달되도록 강제해놓아서 숫자가 아닌 형식이 전달되도 에러를 내보냅니다. 제가 기존에 width와 height 값으로 사용하던 것은 4rem인데 아시다시피 저희는 rem 값을 화면 크기에 따라 유동적으로 바뀌도록 만들어두었기 때문에 next에서 만든대로 px 값으로 강제하게 된다면 아이콘 크기는 그대로고 글자와 슬라이더의 크기만 화면 크기에 따라 계속 바뀌게 되어 반응형도 아니게 될 뿐더러 보기가 어렵습니다.

2022-12-23 11:40 UTC, LAH1203 commented on frontend/src/components/Header/Slider/Login/index.tsx
> +            d="M16.5938 24.2568C16.5938 24.9903 16.8851 25.6938 17.4038 26.2124C17.9224 26.7311 18.6259 27.0225 19.3594 27.0225C20.0929 27.0225 20.7963 26.7311 21.315 26.2124C21.8336 25.6938 22.125 2
[밑의 코멘트](https://github.com/Joribok/Joribok/pull/12#discussion_r1056274453) 참고해주세요.

2022-12-24 09:33 UTC, liswktjs commented on frontend/src/components/Header/Slider/Login/index.tsx
> +import loginSVG from '@/assets/svg/user/login.svg';
흠 Next에서 해당 방식으로 강제하게 된 이유가 실제 프로젝트에서 사용하는 이미지들은 사전에 이미지 크기 들을 정하고 진행하기 때문일까요? 하하하 다들 어떻게 하는 거지 껄껄

2022-12-24 09:33 UTC, liswktjs approved these changes
수고하셨습니다 하리~

2022-12-24 09:34 UTC, merged