[FE] 로그인 페이지 구현
Joribok/Joribok pull request #15
Opened 2022-12-21 14:17 UTC by usageness

## 개발한 기능 목록

- 로그인 페이지 구현
- 버튼 컴포넌트 props 수정

![image](https://user-images.githubusercontent.com/28296575/208925040-b40c0280-e44e-46ae-860c-376c366d16b2.png)

## 공유할 사항

- 지난 샐리 PR (#10) 에서 리뷰에 남겼던 CreatePortal 관련 코드를 Ref를 사용하는 코드로 변경했습니다. 관련 내용은 찾아보겠습니다.
- Button Component에 기본 인자들을 추가로 받아주었습니다. Custom Props을 만들어줬던 컴포넌트라면 꼭 해주어야합니다.
```typescript
const Button = ({
  type = BUTTON_TYPE.SUBMIT,
  size = SIZE.MEDIUM,
  isAvailable = true,
  children,
  ...buttonAttribute // rest parameter로 추가 속성들 받아주기
}: ButtonProps &
  React.DetailedHTMLProps<React.ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>) => {
  // DetailedHTMLProps<T> 를 이용해서 원하는 속성들을 가져와줍니다.
  switch (size) {
    case SIZE.SMALL:
      return (
        <S.SmallButton type={type} isAvailable={isAvailable} {...buttonAttribute}> // rest parameter로 추가 속성 넣어주기
          {children}
        </S.SmallButton>
      );
```
- 유효성을 판정할 정규식을 우선 constant/index에 넣어주었습니다. 회원가입까지 구현하더라도 여기서 한 두개 정도 더 추가될거 같은데 굳이 분리할 필요성을 못느껴서 일단 두었는데, 혹시 의견 있으시면 리뷰로 남겨주세요 :) 

Close #5

2022-12-22 05:13 UTC, liswktjs requested changes
Next와 관련된 이슈상황 어제 정리하다가 알아내서 코멘트로 남겨두었습니다!

2022-12-22 05:13 UTC, liswktjs commented on frontend/src/util/CreatePortal.tsx
> +    portalRef.current = document.querySelector<HTMLElement>(`#${modalId}`);
Next는 브라우저 환경에서가 아닌 서버 환경에서 코드를 실행시킨 후에, 완성된 index.html파일을 브라우저에 보내주기 때문에 최초의 실행환경은 브라우저가 아니게 됩니다. 그런데 document는 브라우저에 종속적인 속성이기 때문에 브라우저가 아닌 환경에서 코드를 동작시켰을 때에 에러가 not defined에러가 발생하게 됩니다! 그래서 useEffect를 활용해서 화면상에 렌더링 된 이후에 document를 찾도록 실행을 지연시켜야합니다

2022-12-22 05:13 UTC, liswktjs commented on frontend/src/pages/login/index.tsx
> +import useSnackBar from '@/hooks/useSnackBar';
사소하지만 import 문 순서를 조정하는거 어떨까요  hook끼리 모아두죠

2022-12-22 05:13 UTC, liswktjs commented on frontend/src/components/Button/index.tsx
> +  React.DetailedHTMLProps<React.ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>) => {
오 해당 type을 사용하면 button관련 타입들을 다 가져올 수 있나 보군요

2022-12-22 05:13 UTC, liswktjs commented on frontend/src/constants/index.ts
> +  PASSWORD: /^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,19}$/,
정규식에서 eslint에러가 발생하나요?

2022-12-22 05:13 UTC, liswktjs commented on frontend/src/hooks/useInput.ts
> +  return [value, changeValue] as const;
해당 부분에서 return할때에 as const로 처리한 이유가 있나요?

2022-12-22 05:13 UTC, liswktjs commented on frontend/src/hooks/useInput.ts
> +const useInput = <T extends useInputProps>(initialValue: T) => {
👍

2022-12-22 05:13 UTC, liswktjs commented on frontend/src/pages/login/index.styles.tsx
> +  }
오호 새로운 컨벤션이군요 네이밍 따로 안 해도 되고 편하겠네요

2022-12-22 05:13 UTC, liswktjs commented on frontend/src/pages/login/index.tsx
> +      console.log('?');
console.log는 어떤 이유로 남겨두셨나요?

2022-12-22 05:13 UTC, liswktjs commented on frontend/src/pages/login/index.tsx
> +        </S.InputLabelContainer>
개인 취향으로 해당 부분도 컴포넌트로 분리하고 싶은데, 사실 애매 하기도 해서 세지 마음대로 해주세요!

2022-12-22 08:45 UTC, usageness commented on frontend/src/components/Button/index.tsx
> +  React.DetailedHTMLProps<React.ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>) => {
맞습니다~ `DetailedHTMLProps` 도 제네릭으로 타입을 받고 있어서 해당 HTML 요소의 타입을 다 가져올 수 있습니다!

2022-12-22 08:45 UTC, usageness commented on frontend/src/constants/index.ts
> +  PASSWORD: /^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,19}$/,
그러게 말이에요 호호..

2022-12-22 08:49 UTC, usageness commented on frontend/src/hooks/useInput.ts
> +  return [value, changeValue] as const;
as const로 처리해주면 훅을 사용할때 배열의 인덱스에 따라 타입이 고정됩니다.
위 예시에서 as const를 제거하면 아래처럼 value와 setter의 타입을 구분하지 못하게 추론되어 불편해져요!

![image](https://user-images.githubusercontent.com/28296575/209095038-8df2598a-c77f-4296-a9ef-16f55f8a4bc8.png)

2022-12-22 08:49 UTC, usageness commented on frontend/src/pages/login/index.styles.tsx
> +  }
불필요한 네이밍은 최대한 줄였습니다!

2022-12-22 08:50 UTC, usageness commented on frontend/src/pages/login/index.tsx
> +      console.log('?');
아차차

2022-12-22 08:50 UTC, usageness commented on frontend/src/pages/login/index.tsx
> +        </S.InputLabelContainer>
회원가입 페이지 구현하면서 한 번 시도해보겠습니다 ㅎㅎ

2022-12-22 09:59 UTC, usageness commented on frontend/src/util/CreatePortal.tsx
> +    portalRef.current = document.querySelector<HTMLElement>(`#${modalId}`);
브라우저 속성으로 옮겨진 후에 찾도록 해도 안뜨더라구요...
오류는 안나는데.. 아예 안뜨는...
연구 대상입니다

2022-12-23 03:02 UTC, LAH1203 approved these changes
세지 수고하셨습니다~ 딱히 크리티컬한 이슈나 코멘트는 없어서 바로 어프로브할게요! 나중에 코멘트 확인해주세욥

2022-12-23 03:02 UTC, LAH1203 commented on frontend/src/components/Button/index.tsx
> +  React.DetailedHTMLProps<React.ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>) => {
~아 추가하는거 깜빡했다...~
ㅎㅎ감사합니다~

2022-12-23 03:02 UTC, LAH1203 commented on frontend/src/constants/index.ts
> +  PASSWORD: /^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,19}$/,
잉 전 왜 제거해도 안나죠 해명해주세요 세지

2022-12-23 03:02 UTC, LAH1203 commented on frontend/src/pages/login/index.stories.tsx
> +  },
크.. 역시

2022-12-23 03:02 UTC, LAH1203 commented on frontend/src/pages/login/index.styles.tsx
> +  }
아주 좋아요~

2022-12-23 03:02 UTC, LAH1203 commented on frontend/src/pages/login/index.styles.tsx
> +  line-height: 1.2rem;
line-height가 font-size를 따라가지 않아서 강제해주신 걸까요?.?

2022-12-23 03:02 UTC, LAH1203 commented on frontend/src/pages/login/index.tsx
> +      console.log('?');
유차차

2022-12-23 03:02 UTC, LAH1203 commented on frontend/src/pages/login/index.tsx
> +  }, [id, password]);
근데 궁금한 게 이러면 전에 Input 컴포넌트 구현하실 때 invalid하면 빨간 배경 뜨기로 한건 여기서는 적용하지 않는 건가요? 코드 상에서 따로 존재하지 않고 실행할 때도 보이진 않더라고요

2022-12-23 03:02 UTC, LAH1203 commented on frontend/src/pages/login/index.tsx
> +        아직 가입하지 않으셨다면, <Link href={'/login#'}>회원가입</Link> 하러 갈까요?
당.장.가.입.해

2022-12-23 03:02 UTC, LAH1203 commented on frontend/src/styles/global.tsx
> +    text-decoration: none;
오호 글로벌 스타일로 추가가 되었군요~ 좋아요~

2022-12-24 11:07 UTC, usageness commented on frontend/src/constants/index.ts
> +  PASSWORD: /^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,19}$/,
다시 제거하니까 안나네요 뭐지...? 일단 삭제할게요~

2022-12-24 11:07 UTC, usageness commented on frontend/src/pages/login/index.styles.tsx
> +  line-height: 1.2rem;
미리보기로 볼때 line-height가 묘하게 안맞더라구요..?
그래서 명시적으로 지정해주었습니다.

2022-12-24 11:09 UTC, usageness commented on frontend/src/pages/login/index.tsx
> +  }, [id, password]);
invalid 한 input은 보통 유효성이 안맞는 경우에 사용하는데,
해당 기능은 로그인보단 회원가입에 적용하는게 맞는것 같다는 생각이 들어요.
지금은 invalid시 스낵바로 알려주고 있으니 충분하다고 봅니다!

2022-12-24 11:12 UTC, usageness commented
수정사항 반영해서 다시 리뷰 요청드립니다~

2022-12-26 04:55 UTC, liswktjs approved these changes
변경사항 확인했습니다~

2022-12-26 05:43 UTC, merged