[FE] 행운 뽑기 페이지 구현
Joribok/Joribok pull request #18
Opened 2022-12-23 18:21 UTC by LAH1203

## 개발한 기능 목록

- 행운 뽑기 페이지 UI 및 애니메이션 제작
- msw mocking 및 api 통신

https://user-images.githubusercontent.com/57928612/209386390-19a4ba18-a9a5-45e0-9bee-5a75a094f357.mov

## 공유할 사항

- msw mocking 시 next.js는 ssr이다보니 처음 실행 시 노드 환경에서 실행되어 server가 비동기적으로 받아와져 undefined일 수가 있습니다. 이는 계속해서 터미널 단에서 에러가 났기에 해결할 방법을 찾아보았고, 다이나믹 임포트를 적용시켰습니다.
```js
if (typeof window === 'undefined') {
  import('./server').then(({ server }) => {
    server.listen();
  });
} else {
  import('./browser').then(({ worker }) => {
    worker.start();
  });
}
```
- 액세스 토큰을 헤더에 넣는 것으로 axios interceptors를 활용하였습니다. 우선 지금은 로그인 시 받아오는 액세스 토큰을 어디에 저장할지 따로 정한 바가 없어 액세스 토큰에 빈 값을 넣어 요청을 보내도록 만들었습니다. 추후 회의를 통해 정해지면 수정할 예정입니다.
- 약 두 시간에 걸쳐 운세, 행운의 물건, 행운의 색깔 배열을 열심히 채워보았습니다. 추가할 사항이 있다면 언제나 환영합니다. ~이제 힘들어서 못하겠어요.~

close #17

2022-12-24 14:39 UTC, usageness approved these changes
코드를 너무 잘 짜주셔서 고칠만한 부분은 안보이네요! ㅎㅎ
고생하셨습니다~~

2022-12-24 14:39 UTC, usageness commented on frontend/src/api/index.ts
> +    // TODO: 추후 액세스토큰을 어디에 저장할지 결정되면 수정
👍

2022-12-24 14:39 UTC, usageness commented on frontend/src/components/LuckyBox/CommentBox/index.styles.tsx
> +  max-width: 100%;
오.. 컨텐츠가 부모 요소의 크기를 넘어가는 경우가 있나요?

2022-12-24 14:39 UTC, usageness commented on frontend/src/components/LuckyBox/CommentBox/index.styles.tsx
> +`;
역시 하리... 👍👍👍

2022-12-24 14:39 UTC, usageness commented on frontend/src/hooks/useTyping.tsx
> +};
하리... 천재이신가요...?

2022-12-24 14:39 UTC, usageness commented on frontend/src/mocks/handlers/lucky.ts
> +  '엑스박스',
사심이 그득...

2022-12-24 14:39 UTC, usageness commented on frontend/src/pages/lucky/index.tsx
> +  // eslint-disable-next-line react-hooks/rules-of-hooks
오잉..? 훅에서 린트 에러가 나나요?

2022-12-26 05:45 UTC, liswktjs requested changes
하리 애니메이션 너무 이쁩니다.... 못하는게 뭔가요 

상수같은거랑 질문 몇가지 달았습니다!

2022-12-26 05:45 UTC, liswktjs commented on frontend/src/api/index.ts
> +    // TODO: 추후 액세스토큰을 어디에 저장할지 결정되면 수정
오호 서버랑 연결했을때에 처리되는 구간이보군요

2022-12-26 05:45 UTC, liswktjs commented on frontend/src/api/index.ts
> +    }
만약에 accessToken이 빈 문자열로 로컬에 저장되어 있다면 해당 케이스에 대한 처리는 백에서 진행하는 걸로 처리되는 걸까요?

2022-12-26 05:45 UTC, liswktjs commented on frontend/src/api/index.ts
> +  },
오호 이런식으로 에러 상황에 대해서 처리하신 이유가 있을까요?

2022-12-26 05:45 UTC, liswktjs commented on frontend/src/api/index.ts
> +  },
저는 React-query에서 error 처리 옵션이 있다보니 axios단에서는 따로 처리를 안해줬어서 더 궁금해요 ! 😘

2022-12-26 05:45 UTC, liswktjs commented on frontend/src/components/LuckyBox/CommentBox/index.styles.tsx
> +  animation: ${blinkAnimation} 0.5s step-end infinite alternate;
너무 이뻐요 👍

2022-12-26 05:45 UTC, liswktjs commented on frontend/src/components/LuckyBox/index.tsx
> +const animationDelay = 5;
상수 어떠신가요....? 😍

2022-12-26 05:45 UTC, liswktjs commented on frontend/src/hooks/useTyping.tsx
> +  }, [text, delay]);
외워야지... 📝

2022-12-26 05:45 UTC, liswktjs commented on frontend/src/mocks/handlers/lucky.ts
> +  '라인프렌즈',
💖

2022-12-26 05:45 UTC, liswktjs commented on frontend/src/mocks/handlers/lucky.ts
> +const fortunes = [
해당 데이터는 따로 파일 분리하는게 어떨까요?

2022-12-26 05:45 UTC, liswktjs commented on frontend/src/mocks/index.ts
> +}
👍👍

2023-01-03 07:28 UTC, LAH1203 commented on frontend/src/components/LuckyBox/CommentBox/index.styles.tsx
> +  max-width: 100%;
오.. 이것저것 실행해보던 흔적이 남아있었군요,, 지우겠습니당 알려주셔서 감사합니다!

2023-01-03 07:29 UTC, LAH1203 commented on frontend/src/hooks/useTyping.tsx
> +};
제가요..? 🤔

2023-01-03 07:29 UTC, LAH1203 commented on frontend/src/mocks/handlers/lucky.ts
> +  '엑스박스',
들켰당,, 하핳

2023-01-03 07:29 UTC, LAH1203 commented on frontend/src/pages/lucky/index.tsx
> +  // eslint-disable-next-line react-hooks/rules-of-hooks
아 에러가 났었어서 주석을 추가했었는데 다시 보니 다른 해결책이 있었네요! 주석 제거하고 해결하였습니다 :)

2023-01-03 07:29 UTC, LAH1203 commented on frontend/src/api/index.ts
> +    // TODO: 추후 액세스토큰을 어디에 저장할지 결정되면 수정
서버랑 연결하기 보다는 액세스토큰을 서버에서 받아서 프론트에서는 어디에 저장할지를 아직 정하지 않았던 것 같아서 우선은 주석으로 달아두었습니다! 금요일에 회의할 때 이 부분도 같이 얘기해보면 좋을 것 같아요 :D

2023-01-03 07:29 UTC, LAH1203 commented on frontend/src/api/index.ts
> +    }
저희가 api 문서를 작성하면서 액세스 토큰의 유효성 여부를 백에서 검증하기로 하고 에러 세분화를 했던 것으로 기억해요. 그래서 빈 문자열도 유효성 여부에서 걸러지니 백에서 진행해도 좋을 것 같다고 생각했어요! 혹시 다른 의견이 있으시다면 남겨주세요 :)

2023-01-03 07:29 UTC, LAH1203 commented on frontend/src/api/index.ts
> +  },
음 이 부분은 [axios의 인터셉터 문서](https://axios-http.com/kr/docs/interceptors)를 참고해서 만들어보았는데요..! 지금은 에러에 대해서 공통적으로 처리해주는 바가 없어 전달된 에러를 바로 reject하도록 했는데, 만약 해당 인터셉터 인스턴스를 통한 통신에서 공통적으로 나는 에러 (예를 들면 토큰 에러?) 같은 부분은 여기에서 컨트롤할 수도 있겠다고 생각해서 우선은 남겨보았어요. 일단 지금은 사용하지 않으니 제거하는 편이 나을까요?.?

2023-01-03 07:29 UTC, LAH1203 commented on frontend/src/components/LuckyBox/index.tsx
> +const animationDelay = 5;
음음 constants 폴더로 빼보면 어떻겠냐는 말씀이시겠죠? 빼보겠습니당 !

2023-01-03 07:29 UTC, LAH1203 commented on frontend/src/hooks/useTyping.tsx
> +  }, [text, delay]);
제 부끄러운 코드 외우지 마시고,, 구글링하면 더 멋진 코드들이 많잖아요 🫣 예를 들면 샐리 코드라든가, 세지 코드라든가 하는거 흠흠,,,

2023-01-03 07:29 UTC, LAH1203 commented on frontend/src/mocks/handlers/lucky.ts
> +  '라인프렌즈',
(사실 샐리를 넣을까 망설였다는 비밀)

2023-01-03 07:29 UTC, LAH1203 commented on frontend/src/mocks/handlers/lucky.ts
> +const fortunes = [
오 샐리가 json 파일로 분리했던 것처럼 말씀이시죠? 한번 해볼게요!

2023-01-03 07:37 UTC, usageness commented on frontend/src/hooks/useTyping.tsx
> +  }, [text, delay]);
네?

2023-01-05 13:41 UTC, liswktjs approved these changes
하리 수고하셨습니다 👍

2023-01-05 13:41 UTC, liswktjs commented on frontend/src/mocks/data/fortunes.json
> +{
👍👍

2023-01-06 04:13 UTC, merged