[FE] 회원가입 페이지 구현
Joribok/Joribok pull request #20
Opened 2023-01-04 09:10 UTC by usageness

## 개발한 기능 목록
- 회원가입 페이지 개발
- msw mocking 및 api 통신

![joribok_main_to_signup](https://user-images.githubusercontent.com/28296575/210520031-0439b904-f131-4743-b149-51267f3dc112.gif)
![joribok_signup](https://user-images.githubusercontent.com/28296575/210520041-2cca24e3-69a6-4c1e-b3e6-524478b1c6e2.gif)
![joribok_signup_error](https://user-images.githubusercontent.com/28296575/210520051-6ef2e4c5-db3d-4004-8bb3-b7476fbe40ef.gif)

## 공유할 사항

- 스토리북에서 next.js의 라우터를 사용하는게 생각보다 쉽지 않은것 같습니다. 좀 더 찾아봐야겠지만 공식적으로 지원하는 문서는 없는 것 같네요. addon 레포에서 제공하는 문서는 이전 버전 (next 12) 입니다.
- gif는 안찍었는데 로그인 액션도 일단 모킹해두었습니다.
- 로그인 시 받아오는 액세스 토큰을 어디에 저장할지 따로 정한 바가 없어 우선 따로 저장하지 않았습니다. 금요일에 논의해보아요~
- 페이지 스토리북은 기존에 해뒀던 로그인 페이지를 제외하고 뺐습니다~
- get이 아닌 post 등의 요청은 useMutate를 활용했는데 이 부분은 훅으로 뺐더니 깔끔해지더라구요. 패턴화 시켜서 사용하면 좋을 것 같습니다. 참고 : [refactor: 로그인 로직 useLogin 훅으로 분리](https://github.com/Joribok/Joribok/commit/dafdaf09609a839e40f7523fe1d5993cb0057d3e)

close #19

2023-01-05 14:16 UTC, liswktjs requested changes
개인적으로 입력 폼에 글씨 작성할때 빨간색 효과가 제일 마음에 듭니다 👍
추가적으로 스토리북에서 login 부분에 에러가 나던데 이 부분 확인 부탁드립니다

2023-01-05 14:16 UTC, liswktjs commented on frontend/package.json
> +    "build-sb": "build-storybook"
손가락을 지켜줄 축약형...👍

2023-01-05 14:16 UTC, liswktjs commented on frontend/src/hooks/useLogin.ts
> +import { requestLogin } from '@/api/auth';
import문 순서 api와 관련된거는 외부 라이브러리에서 import한거 아래에 두는 게 어떨까요?

2023-01-05 14:16 UTC, liswktjs commented on frontend/src/hooks/useLogin.ts
> +import { requestLogin } from '@/api/auth';
이참에 Import문 prettier같은걸로 자동화하는것도 좋을 것 같네요!

2023-01-05 14:16 UTC, liswktjs commented on frontend/src/hooks/useLogin.ts
> +      router.push('/');
이렇게 Push로 처리하게 되면 어떻게 동작하게 되는건가요? 
성공시 바로 페이지가 이동이 되는 걸까요?

2023-01-05 14:16 UTC, liswktjs commented on frontend/src/hooks/useSignup.ts
> +import { requestSignup } from '@/api/auth';
해당 Impor문도 동일하게 제안합니다!

2023-01-05 14:16 UTC, liswktjs commented on frontend/src/hooks/useSignup.ts
> +  });
깔끔하네요 onSuccess, onError로 처리하니

2023-01-05 14:16 UTC, liswktjs commented on frontend/src/pages/signup/index.tsx
> +import useSignup from '@/hooks/useSignup';
이 훅을 hook끼리 묶으면 좋을 것 같아요

2023-01-05 14:16 UTC, liswktjs commented on frontend/src/pages/signup/index.tsx
> +          </S.InputContainer>
이렇게 컴포넌트로 분리해서 재사용하는거 어떤가요?

2023-01-09 09:13 UTC, LAH1203 approved these changes
샐리가 먼저 남겨주시기도 했고, 코드가 깔끔해서 남길 코멘트가 없네요ㅎㅎ; 머쓱 😅 간단하게 하나만 남겨보았습니다 하핳

개인적으로 회원가입 페이지 코드가 너무 길어서 한번에 보기에 조금 힘들었어요. 검증 로직 부분을 커스텀훅으로 분리하거나 샐리 말처럼 재사용할 수 있는 Input 부분을 컴포넌트화 시켜보는 것도 좋을 것 같아요~

수고하셨습니다!

2023-01-09 09:13 UTC, LAH1203 commented on frontend/src/types/user.ts
> +};
interface 말고 type으로 정의해주신 이유가 있나요?
개인적인 의견을 내보자면, UserLoginData가 UserData에서 nickname만 빠진 값이라면 Omit이나 Pick을 활용해도 좋을 것 같아요~

2023-01-16 07:54 UTC, usageness commented on frontend/src/hooks/useLogin.ts
> +      router.push('/');
네! 성공적으로 통신이 이루어지면 바로 페이지가 이동되고,
실패하면 onFailure 단이 실행되게 됩니다~

2023-01-16 08:22 UTC, usageness commented on frontend/src/types/user.ts
> +};
좋은 생각이에요!
전체 데이터 타입을 가진 UserData를 interface로 선언하고,
type UserLoginData에서 Pick을 활용해 특정 데이터만 가져오는것으로 변경하였습니다!

```typescript
export interface UserData {
  id: string;
  password: string;
  nickname: string;
}

export type UserLoginData = Pick<UserData, 'id' | 'password'>;
```

2023-01-16 10:06 UTC, usageness commented on frontend/src/hooks/useLogin.ts
> +import { requestLogin } from '@/api/auth';
prettier import를 적용해서 자동으로 정렬되도록 하겠습니다!

2023-01-16 14:30 UTC, usageness commented on frontend/src/pages/signup/index.tsx
> +          </S.InputContainer>
컴포넌트로 분리 + 리스트로 만들어서 순회까지 했습니다!

```tsx
<S.InputSection>
  {inputList.map(item => (
    <ValidateInputLabel
      key={item.state}
      key={item.label}
      data={item.state}
      changeData={item.changeState}
      isValidateData={item.isValidateState}
      inputType={item.inputType}
      label={item.label}
      message={item.message}
    />
  ))}
</S.InputSection>
```

2023-01-16 15:04 UTC, usageness commented
리뷰 주셨던 내용 모두 수정 완료했습니다!
다시 한 번 확인 부탁드려요~

2023-01-17 12:10 UTC, liswktjs approved these changes
작동도 모두 확인했습니다 !

2023-01-17 12:10 UTC, liswktjs commented on frontend/.prettierrc.json
> +  "importOrderSortSpecifiers": true
👍👍

2023-01-17 13:38 UTC, merged