[FE] 글 작성 페이지 구현
Joribok/Joribok pull request #21
Opened 2023-01-15 14:33 UTC by liswktjs

close #14

## 구현 사항 

- [x] 계획을 입력할 수 있다
- [x] 중복되는 계획은 입력할 수 없다
- [x] 계획이 10개 이상 넘어갈 경우 snackBar로 에러 메세지를 보여준다
- [x] 생성된 계획들을 볼 수 있는 height는 정해져 있고 여러개의 계획이 생성되어 넘칠 경우 해당 부분들은 scroll로 처리한다
- [x]  타이틀에 유저의 닉네임을 보여준다 (상태값에서 가져오기)
- [x] 작성한 계획을 삭제할 수 있다
- [x] 유저가 입력한 계획들은 상태로 관리하고 서버로 전송시에 payload에 담아 보낸다
저장 버튼을 누르고 성공할 경우 새롭게 생성된 상세보기페이지로 이동시킨다 (예정)

![스크린샷 2023-01-15 오후 11 28 41](https://user-images.githubusercontent.com/60773373/212546623-963aaf90-5641-4a28-b12f-e0d0b1b42c72.png)

## 공유 사항 

- PlanBox들에 대해서 마우스를 올렸을 때에 애니메이션 적용하였습니다 
   - 페이지가 동적으로 보여주고 싶어서 마우스를 올렸을 때에 애니메이션을 적용하였습니다 다만, 모바일로 대응하게 되면 부드럽게 애니메이션이 안보여질 것 같아서 의견을 구하고 싶습니다 
- 계획 생성 api관련 
  - 해당 api 관련해서 자세히 이야기가 안 된 것 같아서, 나중에 서버 구현하면서 같이 이야기 진행하면 좋을 것 같습니다 
- 비동기 통신 관련 에러 처리
  - 생각해보니 비동기 통신 관련해서 어떻게 에러 처리를 해야할지 자세히 이야기를 진행하지 못한 것 같아요 에러바운더리를 구현해서 처리할 수도 있을 것 같고, axios를 활용하고 있으니 해당 부분을 활용하거나, react-query등 여러 방법이 있을 것 같은데 어떻게 처리하면 좋을지 이야기 해보면 좋을 것 같습니다

2023-01-16 02:19 UTC, LAH1203 requested changes
안녕하세요 샐리! 꼼꼼하게 올려주신 부분들 확인해서 리뷰 남겨봤습니다 :) 편하실 때 확인해주세요!

아 그리고 이건 샐리 예전 PR 내용이긴 한데요! 전에 메인 화면에서 `??개의 계획이 모여있어요`라고 적혀있는 부분에 padding을 적용해주셨는데 지금 다시 확인해보니 가운데 정렬이 제대로 이루어지지 않더라고요. 아마 box-sizing이 적용되지 않아 padding에 밀려서 그런 것 같습니다 ㅎㅎ 이 부분도 확인해주시면 감사하겠습니다~

2023-01-16 02:19 UTC, LAH1203 commented on frontend/src/components/PlanBox/animation.module.css
> +  animation: bounce 0.3s infinite;
애니메이션 바운스가 너무 박력있게 딱딱 되다보니 볼 때마다 움찔하게 되더라고요. 혹시 `alternate`를 적용해서 좀 더 부드럽게 애니메이션을 재생해보는 건 어떠실까요 ㅎ.ㅎ

2023-01-16 02:19 UTC, LAH1203 commented on frontend/src/components/PlanBox/index.styles.tsx
> +export const Content = styled.div``;
이 아무 스타일 없는 컴포넌트는 뭘까요 ?.?

2023-01-16 02:19 UTC, LAH1203 commented on frontend/src/components/PlanBox/index.styles.tsx
> +  min-height: 50px;
최소 높이를 픽셀로 주신 이유가 있나요?

2023-01-16 02:19 UTC, LAH1203 commented on frontend/src/components/PlanBox/index.tsx
> +      <S.DeleteButton onClick={onDeleteButtonClick} aria-label={'계획 삭제하기'}>
aria-label 뒤의 중괄호는 삭제해도 될 것 같네요 :)

2023-01-16 02:19 UTC, LAH1203 commented on frontend/src/components/PlanBox/index.tsx
> +      onMouseOut={() => setAnimationName('')}
위의 randomColor는 함수를 잘 빼주셨으니, 이 아이들도 함수로 빼주면 어떨까요? 한다면 함수를 세 개로 쪼개기보다는 커링을 응용해서 하나로 만들면 좋겠네요!

2023-01-16 02:19 UTC, LAH1203 commented on frontend/src/components/PlanBox/index.tsx
> +  const color = useMemo(() => getRandomColor(), [plan]);
color 말고 다른 네이밍은 어떠실까요? 랜덤한 색깔이라는 의미를 가져오니 그냥 밑의 props처럼 randomColor라는 이름을 사용해도 좋을 것 같아요.

2023-01-16 02:19 UTC, LAH1203 commented on frontend/src/pages/write-plan/index.styles.tsx
> +  font-size: 20px;
그럼 이 친구는 폰트 사이즈가 화면에 따라 유동적이지 않고 고정인건가요? 작은 폰에서 봤을 때는 크기가 너무 커보여요 ㅠㅠ

2023-01-16 02:19 UTC, LAH1203 commented on frontend/src/pages/write-plan/index.styles.tsx
> +    width: 50px;
작은 폰에서는 버튼이 깨져보여요!

![image](https://user-images.githubusercontent.com/57928612/212583589-bdfb8b2f-630d-4dee-8a82-f7711f9a8fe0.png)

2023-01-16 02:19 UTC, LAH1203 commented on frontend/src/pages/write-plan/index.tsx
> +  };
빈 문자열이나 공백(스페이스, 엔터, 탭 등)만 입력되는 경우도 막아주셔야 할 것 같아요!

2023-01-16 02:19 UTC, LAH1203 commented on frontend/src/pages/write-plan/index.tsx
> +        <Input type={'text'} value={plan} onChange={onPlanInputChange} />
여기도 type 뒤에 중괄호는 제거해도 되겠네요~

2023-01-16 02:19 UTC, LAH1203 commented on frontend/src/pages/write-plan/index.tsx
> +              key={index}
어차피 삭제하거나 하면 리렌더링이 되니 key를 인덱스로 써주신걸까요?
중복되는 계획은 적지 못하도록 막아주셨으니 계획을 key로 두시는 건 어떤가요!

2023-01-16 02:19 UTC, LAH1203 commented on frontend/src/pages/write-plan/index.tsx
> +  };
실시간성이 필요하지 않은 부분이니 ref를 사용해서 비제어로 가보시는 건 어떤가요?

2023-01-16 02:19 UTC, LAH1203 commented on frontend/src/pages/write-plan/index.tsx
> +        <Input type={'text'} value={plan} onChange={onPlanInputChange} />
이건 개인적인 소망이지만,, 엔터 입력을 인지하도록 추가해서 엔터만 입력해도 계획이 추가되도록 하는 건 어떠신가요 ㅎ.ㅎ

2023-01-17 12:11 UTC, liswktjs commented on frontend/src/components/PlanBox/animation.module.css
> +  animation: bounce 0.3s infinite;
오 역시 하리 좋은 제안이네요 수정해보겠습니다!

2023-01-24 05:53 UTC, usageness approved these changes
리뷰를 너무 늦게 드리네요 ㅠㅠ 미안해요 샐리
우선 대부분은 하리가 짚어주었던 부분이라 제가 더 드릴 리뷰는 없는 것 같아요.

모바일 애니메이션 부분은 지금도 괜찮은 것 같아서 크게 신경쓰지 않아도 될거 같습니다~
이대로도 좋아요!

비동기 에러 처리는 에러 처리를 담당하는 전역 객체를 하나 두고,
우리가 지금 리액트 쿼리를 사용하고 있으니 에러가 발생하면
여기서 호출해주면 될 것 같다는 생각입니다!
이걸 잘 관리해 줄 수 있는 친구를 하나 만들어보는게 좋겠네요 :)

고생하셨습니다!

2023-01-24 05:53 UTC, usageness commented on frontend/src/pages/write-plan/index.tsx
> +      showSnackBar('계획은 입력해주세요');
ㅋㅋㅋㅋㅋㅋ 계획 입력 안했다고 혼내는 것 같아요

2023-01-24 05:53 UTC, usageness commented on frontend/src/pages/write-plan/index.tsx
> +  const onPlanConfirmButtonClick = () => {
아래쪽에 `on~~~Click` 도 포함하는 코멘트인데,
단순히 '클릭했다' 라는 이름은 함수 이름으로 충분하지 않은것 같아요!
좀 더 직관적인 네이밍은 없을까요?

2023-01-31 05:50 UTC, liswktjs commented on frontend/src/components/PlanBox/animation.module.css
> +  animation: bounce 0.3s infinite;
하리 천재에요? alternative로 하니까 더 부드럽게 보이고 좋아요 👍

2023-01-31 05:56 UTC, liswktjs commented on frontend/src/components/PlanBox/index.styles.tsx
> +export const Content = styled.div``;
해당 컴포넌트는 스타일이 없긴한데 저는 스타일이 없어도 명시적으로 해당 컴포넌트가 어떤 역할을 하는지 명시하는 편이 좋다고 생각해서 남겨뒀어요!

2023-01-31 05:57 UTC, liswktjs commented on frontend/src/components/PlanBox/index.styles.tsx
> +  min-height: 50px;
엇 이부분 추후에 rem으로 바꾼다고 하고 교체를 안했네요 하핫 반영해서 수정하겠습니다!

2023-01-31 06:04 UTC, liswktjs commented on frontend/src/components/PlanBox/index.tsx
> +  const color = useMemo(() => getRandomColor(), [plan]);
그냥 color로 네이밍을 하면 혼동이 올수도 있겠네요! 바로 수정하겠습니다

2023-01-31 06:05 UTC, liswktjs commented on frontend/src/pages/write-plan/index.styles.tsx
> +  font-size: 20px;
어엇! px를 rem으로 반환한다고 하고 하나씩 빼먹었네요
font size 조금 줄이고 rem으로 변경하겠습니다!

2023-01-31 06:06 UTC, liswktjs commented on frontend/src/pages/write-plan/index.styles.tsx
> +    width: 50px;
이럴수가! 😭

2023-01-31 06:17 UTC, liswktjs commented on frontend/src/pages/write-plan/index.styles.tsx
> +    width: 50px;
해당 부분 확인해보니깐 해당 스타일이 적용이 안되고 있더라고요...???? 
(나의 노트북이 이상한건가) 그래서 size prop으로 SMALL을 넘겨주는 것으로 수정하였습니다

2023-01-31 06:17 UTC, liswktjs commented on frontend/src/pages/write-plan/index.tsx
> +  };
공백 딱 대 🔪

2023-01-31 06:18 UTC, liswktjs commented on frontend/src/pages/write-plan/index.tsx
> +        <Input type={'text'} value={plan} onChange={onPlanInputChange} />
form....form으로 바꾸겠습니다

2023-01-31 06:20 UTC, liswktjs commented on frontend/src/pages/write-plan/index.tsx
> +      showSnackBar('계획은 입력해주세요');
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 계획을 입력해주세요!!

2023-01-31 06:21 UTC, liswktjs commented on frontend/src/pages/write-plan/index.tsx
> +      showSnackBar('계획은 입력해주세요');
저의 본심이 나와버렸군요

2023-01-31 06:23 UTC, liswktjs commented on frontend/src/pages/write-plan/index.tsx
> +  const onPlanConfirmButtonClick = () => {
onAddPlanButtonClick...?

2023-01-31 08:00 UTC, LAH1203 commented on frontend/src/components/PlanBox/animation.module.css
> +  animation: bounce 0.3s infinite;
ㅋㅋㅋㅋㅋㅋ좋아요~

2023-01-31 08:01 UTC, LAH1203 commented on frontend/src/components/PlanBox/index.styles.tsx
> +export const Content = styled.div``;
아하 그렇군요,, 그럼 그냥 div로 만들 때랑 style된 컴포넌트로 만들 때 빌드에서 무슨 차이가 있나요? 갑자기 궁금해졌는데 비교한 좋은 글을 찾지 못했네요 ㅠ.ㅠ

2023-01-31 08:24 UTC, LAH1203 commented on frontend/src/pages/write-plan/index.styles.tsx
> +    width: 50px;
오 그랬군요 👀 좋아요!

2023-01-31 08:25 UTC, LAH1203 commented on frontend/src/pages/write-plan/index.tsx
> +        <Input type={'text'} value={plan} onChange={onPlanInputChange} />
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ좋아좋아~

2023-02-01 12:08 UTC, liswktjs commented on frontend/src/components/PlanBox/index.styles.tsx
> +export const Content = styled.div``;
저도 자세히는 모르지만, emotion은 기본적으로 css in js니깐 미사용 코드는 검출해서 날아가지 않을까요...?

2023-02-01 12:10 UTC, liswktjs commented on frontend/src/components/PlanBox/index.styles.tsx
> +export const Content = styled.div``;
![스크린샷 2023-02-01 오후 9 10 35](https://user-images.githubusercontent.com/60773373/216038991-a607a49d-b6a2-47c5-98f3-387e96453caa.png)
실제로 돌려보니 이러네요 css 클래스명은 들어가 있군요 하핫

2023-02-01 12:18 UTC, merged