[FE] 마이페이지 구현
Joribok/Joribok pull request #22
Opened 2023-01-18 02:44 UTC by LAH1203

## 개발한 기능 목록

- 작성한 새해 목표
- 새해 목표를 작성하지 않았다면, 작성 페이지 유도 버튼
- 가장 최근에 한 행운 뽑기
- msw mocking

### 새해 목표를 작성한 경우

<img src="https://user-images.githubusercontent.com/57928612/213068709-0c3e956e-369c-4cb2-ba3e-167548d55dfc.png" width="425px" alt="image" />

### 새해 목표를 작성하지 않은 경우

<img src="https://user-images.githubusercontent.com/57928612/213068891-3975c10e-6116-4f03-979c-1a6dc2a7ef0b.png" width="425px" alt="image" />

close #16

2023-01-19 07:30 UTC, liswktjs requested changes
제 로컬에서 작동시켜봤을 때에 이렇게 화면에 렌더링 되네요 

![스크린샷 2023-01-19 오후 4 25 00](https://user-images.githubusercontent.com/60773373/213380472-5ade6f1c-598b-4a24-b941-8a41ddc655b5.png)
ㅋㅋㅋㅋㅋㅋㅋㅋ 재물운 집착 조리복 

아마 msw 관련해서 또는 strict mode여서  에러가 발생하는 듯 한데 다시 한번 확인 부탁드려요!

2023-01-19 07:30 UTC, liswktjs commented on frontend/src/pages/me/index.tsx
> +const Me = () => {
next특성상 파일 이름이 바로 Url이 되버려서 me로 하셨나 보네요 

뭔가 뭔가 애매한데 url로 생각해보면 적절한 것 같아서 일단 좋아요 하하 👍

2023-01-19 07:30 UTC, liswktjs commented on frontend/src/mocks/handlers/me.ts
> +    const fortune = fortunes[Math.floor(Math.random() * fortunes.length)];
범인...? 👀

2023-01-19 11:02 UTC, LAH1203 commented on frontend/src/mocks/handlers/me.ts
> +    const fortune = fortunes[Math.floor(Math.random() * fortunes.length)];
두 번씩 나오는 건 strict mode 때문이긴 한데 이게 로컬에서만 그런거라 끄기도 애매하더라고요..? 전에 strict mode를 제거했더니 왜 제거했냐, 이걸 제거해서 안좋은 점이 뭐가 있냐, 리액트에서 strict mode를 둔 이유가 있지 않겠냐 등등 질문을 많이 들어서 이에 대해 저희끼리 상의하고 빼도 괜찮다고 판단되면 그 때 제거해도 될 것 같습니다!

2023-01-19 13:39 UTC, usageness reviewed
고생했어요 하리~~~
샐리가 남겨준 리뷰에 몇가지 덧붙여봤습니다!

react strict mode 부분은 이야기를 좀 더 해봐야할거 같아요.
관련해서 남긴 코멘트 확인해주세요~~

2023-01-19 13:39 UTC, usageness commented on frontend/src/components/Header/Slider/Login/index.tsx
> +        <Link onClick={closeSlider} href="/me">
문득 든 생각인데 페이지 경로는 상수로 관리하는거 어떻게 생각하시나요!

2023-01-19 13:39 UTC, usageness commented on frontend/src/mocks/handlers/me.ts
> +    const fortune = fortunes[Math.floor(Math.random() * fortunes.length)];
strict mode 자체는 빼도 괜찮을것 같긴한데,
의도적으로 두 번씩 호출해서 문제를 찾아주는게 주 기능이니까
그거에 대한 예외처리를 해주는게 올바른 방향일것 같다는 생각은 드네요...
어떻게 생각하시나요 ㅎㅎ

2023-01-19 13:39 UTC, usageness commented on frontend/src/pages/me/index.tsx
> +  if (!data) return <>loading...</>;
loading용 UI를 하나 만들어두는게 좋겠다는 생각이 드는군요!
suspense를 사용하기가 어려우니
전역 상태로 isLoading 같은걸 하나 관리하면 괜찮을 것 같슴다

2023-01-19 13:39 UTC, usageness commented on frontend/src/styles/global.tsx
> +  }
👍👍

2023-01-27 03:47 UTC, LAH1203 commented on frontend/src/mocks/handlers/me.ts
> +    const fortune = fortunes[Math.floor(Math.random() * fortunes.length)];
요청 함수가 몇 번 불린 건지를 상태로 관리하자는 말씀이실까요?.? 저는 개인적으로 배포에는 불필요한 코드라고 생각해서 없는 편이 낫지 않을까 생각해요!

2023-01-27 03:47 UTC, LAH1203 commented on frontend/src/components/Header/Slider/Login/index.tsx
> +        <Link onClick={closeSlider} href="/me">
여태까지 모든 페이지가 상수화되어 있지 않아 따라가긴 했는데 계속 상수화 시키고 싶다는 생각이 들긴 하더라구요! 한번 모든 페이지 경로를 상수화 시켜볼게요!

2023-01-27 03:47 UTC, LAH1203 commented on frontend/src/pages/me/index.tsx
> +  if (!data) return <>loading...</>;
좋은 생각이네요! 근데 상태를 관리하더라도 isLoading 상태를 보고 UI를 달리 해주는 부분을 _app.tsx에 추가하고 싶었는데 제대로 작동을 하지 않더라고요.. 혹시 다른 방법을 아시거나 추천해주고 싶으신 게 있을까요?

2023-01-27 03:49 UTC, LAH1203 commented on frontend/src/pages/me/index.tsx
> +  if (!data) return <>loading...</>;
추가적으로 이런걸 발견했는데, 아직 실험적인 기능이다보니,, ㅎㅅㅎ

https://beta.nextjs.org/docs/routing/loading-ui

2023-02-02 07:33 UTC, merged