[BE] 서버 초기 설정
Joribok/Joribok pull request #24
Opened 2023-01-20 03:24 UTC by liswktjs

## 구현사항 

- NestJS 설치 
- Article, User 관련 보일러 플레이트 코드 작성

2023-01-20 03:50 UTC, LAH1203 requested changes
와~ 드디어 서버다! 수고하셨습니당 :)

전 아직 nest알못이라 공부를 해봐야겠지만 일단 보여지는 부분에 대해서 간단하게 코멘트 남겨봤어용! 편하실 때 확인해주세요~

2023-01-20 03:50 UTC, LAH1203 commented on backend/src/app.controller.spec.ts
> +describe('AppController', () => {
wow 테스트까지!

2023-01-20 03:50 UTC, LAH1203 commented on backend/src/app.service.ts
> +    return 'Hello World!';
Hello World!

2023-01-20 03:50 UTC, LAH1203 commented on backend/src/article/article.service.ts
> +// import { UpdateArticleDto } from './dto/update-article.dto';
이 파일의 주석이랑 console.log는 나중에 다 삭제하시는건가용?

2023-01-20 03:50 UTC, LAH1203 commented on backend/src/main.ts
> +async function bootstrap() {
이 함수는 화살표 함수가 아니라 일반 함수형으로 표현해주신 이유가 있나요?

2023-01-20 03:50 UTC, LAH1203 commented on backend/src/main.ts
> +  await app.listen(3000);
저희 next도 3000번 포트였나요? (기억이 가물가물... 아마 그랬던 거 같아요!) 프론트, 백 포트가 같으면 로컬에서 같이 실행시키지는 못하지 않을까용?

2023-01-20 03:50 UTC, LAH1203 commented on backend/src/user/entities/user.entity.ts
> +export class User {}
user entity는 아직 비어있는건가요?

2023-01-20 03:50 UTC, LAH1203 commented on backend/test/app.e2e-spec.ts
> +import { AppModule } from './../src/app.module';
흠 nest에도 절대경로를 설정하면 좋겠네요!

2023-01-20 03:50 UTC, LAH1203 commented on frontend/.storybook/preview.js
> +import { ThemeProvider } from '@emotion/react';
잉 이건 뭐지? 잠수함 패치인가요? ㅋㅋㅋㅋㅋㅋㅋ

2023-02-01 12:19 UTC, liswktjs commented on backend/src/app.controller.spec.ts
> +describe('AppController', () => {
만들어줬어요...

2023-02-01 12:19 UTC, liswktjs commented on backend/src/article/article.service.ts
> +// import { UpdateArticleDto } from './dto/update-article.dto';
넵넵 그렇습니다 구현하면서 삭제예정

2023-02-01 12:20 UTC, liswktjs commented on backend/src/main.ts
> +async function bootstrap() {
nest가 해줬어요

2023-02-01 12:20 UTC, liswktjs commented on backend/src/main.ts
> +  await app.listen(3000);
엇 그렇네요! 포트번호 바꿔여 겠어요 일단 3002번 가시죠

2023-02-01 12:24 UTC, liswktjs commented on backend/src/user/entities/user.entity.ts
> +export class User {}
처음부터 시작입니다 후후후

2023-02-01 12:25 UTC, liswktjs commented on frontend/.storybook/preview.js
> +import { ThemeProvider } from '@emotion/react';
ㅋㅋㅋㅋㅋㅋㅋㅋ아...아니 얘가 왜 여기있어

2023-02-01 12:29 UTC, merged