[FE] Button, Box 컴포넌트 구현
Joribok/Joribok pull request #9
Opened 2022-12-15 03:17 UTC by LAH1203

## 개발한 기능 목록

- Button 컴포넌트 구현
- Box 컴포넌트 구현

<img src="https://user-images.githubusercontent.com/57928612/207764344-1a4a2a0e-a571-41b8-bfc8-0fc00135638f.png" width="425px" />

close #3

2022-12-15 04:56 UTC, liswktjs requested changes
![스크린샷 2022-12-15 오후 1 55 13](https://user-images.githubusercontent.com/60773373/207775872-3e99eedd-3f75-4f24-b078-6b82fdec39df.png)
현재 제 로컬에서 실행시켜봤을 때에는 스토리북에 에러가 발견되고 있어요! 확인 부탁드립니다

2022-12-15 04:56 UTC, liswktjs commented on frontend/src/components/Box/index.tsx
> +const Box = ({ color = theme.colors.BLUE_100, align = ALIGN.LEFT, children }: BoxProps) => {
Box 스타일링 할 때에는 color 값을 Prop으로 넘겨줄 때에 theme을 import해서 넘겨주는 구조가 되는 걸까요?

2022-12-15 04:56 UTC, liswktjs commented on frontend/src/components/Box/index.styles.tsx
> +  word-break: break-all;
Box는 따로 min-width ,height를 지정하지 않고 부모 요소로 감싸서 조정하는 방식일까요? 
button들은 width, height 값이 정해져 있어서 질문드립니다!

2022-12-15 04:56 UTC, liswktjs commented on frontend/src/components/Button/index.styles.tsx
> +    background: ${isAvailable ? theme.colors.GREEN_500 : theme.colors.YELLOW_500};
현재 이부분이 스토리북에서 에러를 발생시키는것 같아요! 한 번 확인부탁드립니다~

2022-12-15 05:06 UTC, LAH1203 commented on frontend/src/components/Box/index.tsx
> +const Box = ({ color = theme.colors.BLUE_100, align = ALIGN.LEFT, children }: BoxProps) => {
네! 맞습니다. 정확히는 저희가 emotion을 사용하니 `useTheme` 훅을 사용하여 theme을 가져와 필요한 컬러 값만 뽑아쓰는 형태가 되겠네요 :)

2022-12-15 05:07 UTC, LAH1203 commented on frontend/src/components/Box/index.styles.tsx
> +  word-break: break-all;
네 박스의 경우에는 다른 요소를 감싸주는 것으로 유연함이 필요하다고 생각했어요. 그래서 따로 너비나 길이를 정해주지 않고 부모 요소를 따라가도록 만들어보았습니다 :)

2022-12-15 05:08 UTC, LAH1203 commented on frontend/src/components/Button/index.styles.tsx
> +    background: ${isAvailable ? theme.colors.GREEN_500 : theme.colors.YELLOW_500};
이 부분은 버튼과 박스의 형태가 모두 동일한데도 스토리북이 찾지 못하더라고요! 일단은 컴포넌트 자체는 올바르게 동작해서 여기는 문제가 없다고 판단하였고, 스토리북 자체의 문제라고 생각하여 고치지 않았습니다.
혹시 스토리북의 어디 때문에 그런지 아시나요?.?

2022-12-15 05:38 UTC, LAH1203 commented on frontend/src/components/Button/index.styles.tsx
> +    background: ${isAvailable ? theme.colors.GREEN_500 : theme.colors.YELLOW_500};
드디어 해결했네요... 추가 커밋으로 올렸습니다 ! https://github.com/Joribok/Joribok/pull/9/commits/1bbdbdc6227a8956683e28b0377864b4871bc9e0

2022-12-15 07:35 UTC, usageness requested changes
앞에서 샐리가 잘 리뷰해줘서 딱히 더 드릴게 없네요~!
확인 한 번 부탁드려요~ 👍

2022-12-15 07:35 UTC, usageness commented on frontend/src/components/Button/index.tsx
> +  type = BUTTON_TYPE.SUBMIT,
우리가 다양한 형태로 버튼을 사용하긴 하지만,
Form 데이터를 전송하는 SUBMIT을 기본값으로 주면 다소 적절하지 않을 것 같아요.
이 부분은 그냥 BUTTON으로 주는건 어떨까요?

2022-12-15 07:35 UTC, usageness commented on frontend/src/styles/global.tsx
> +    font-family: 'IBMPlexSansKR-Regular';
혹시 나중에라도 이 폰트의 woff2 형식 CDN을 찾으면 이걸로 교체하는게 좋을 것 같네요!
woff만 있어서 좀 신경쓰이긴 했는데 저는 못 찾았습니다 ㅠ

2022-12-15 12:45 UTC, liswktjs approved these changes
변경사항 확인했습니다!
역시 알수없는 에러는 코드 때문이였네요

2022-12-16 09:00 UTC, LAH1203 commented on frontend/src/components/Button/index.tsx
> +  type = BUTTON_TYPE.SUBMIT,
사실 이 부분은 일반 HTML 버튼의 사양을 따라가면 좋을 것 같아서 submit으로 한거긴 해요. 혹시 button으로 하면 좋은 이유가 있을까요?

2022-12-16 09:00 UTC, LAH1203 commented on frontend/src/styles/global.tsx
> +    font-family: 'IBMPlexSansKR-Regular';
ㅠ.ㅠ woff2로 지원해줘 폰트 제작자!

2022-12-16 09:05 UTC, usageness commented on frontend/src/components/Button/index.tsx
> +  type = BUTTON_TYPE.SUBMIT,
기본 사양을 따라가는거라면 좋아요 ㅎㅎ 잠시 착각하고 있었네요!

2022-12-16 09:05 UTC, usageness approved these changes

2022-12-16 09:06 UTC, merged